name: Java Maven Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: "20"
          distribution: "oracle"
          cache: maven

      - name: Test with Maven
        run: ls
        # run: mvn --batch-mode --update-snapshots -f ../NullPointerException/ClientCLI/pom.xml test
